# Generated by Django 5.2.3 on 2025-06-11 07:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_listing_submitted_by_alter_listing_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="FontAwesome icon class", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Amenities",
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="energy_rating",
            field=models.CharField(
                blank=True, help_text="A+ to F energy rating", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="hoa_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly HOA fee",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("house", "House"),
                    ("apartment", "Apartment"),
                    ("condo", "Condo"),
                    ("townhouse", "Townhouse"),
                    ("villa", "Villa"),
                    ("commercial", "Commercial"),
                    ("land", "Land"),
                    ("other", "Other"),
                ],
                default="house",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="virtual_tour_url",
            field=models.URLField(blank=True, help_text="Link to virtual tour"),
        ),
        migrations.AddField(
            model_name="listing",
            name="year_built",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="amenities",
            field=models.ManyToManyField(blank=True, to="listings.amenity"),
        ),
        migrations.CreateModel(
            name="PropertyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("review", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verified review from actual visitor"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("listing", "user")},
            },
        ),
    ]
