# Generated by Django 5.2.3 on 2025-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_amenity_listing_energy_rating_listing_featured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="deposit_amount",
            field=models.IntegerField(
                blank=True, help_text="Security deposit for rent", null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="listing_type",
            field=models.CharField(
                choices=[
                    ("sale", "For Sale"),
                    ("rent", "For Rent"),
                    ("both", "Sale or Rent"),
                ],
                default="sale",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="rent_price",
            field=models.IntegerField(
                blank=True, help_text="Monthly rent price", null=True
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.IntegerField(help_text="Price for sale"),
        ),
    ]
