# Generated by Django 5.2.3 on 2025-06-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="gallery_image_1",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects/gallery/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="gallery_image_2",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects/gallery/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="gallery_image_3",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects/gallery/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="gallery_image_4",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects/gallery/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="gallery_image_5",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects/gallery/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="main_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects/%Y/%m/%d/"
            ),
        ),
    ]
