# Generated by Django 5.2.3 on 2025-06-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_gallery_image_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="gallery_image_6",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects/gallery/%Y/%m/%d/"
            ),
        ),
    ]
