bedroom_choices = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10
}

price_choices = {
    '100000': '$100,000',
    '200000': '$200,000',
    '300000': '$300,000',
    '400000': '$400,000',
    '500000': '$500,000',
    '600000': '$600,000',
    '700000': '$700,000',
    '800000': '$800,000',
    '900000': '$900,000',
    '1000000': '$1M+',
}

property_type_choices = {
    'house': 'House',
    'apartment': 'Apartment',
    'condo': 'Condo',
    'townhouse': 'Townhouse',
    'villa': 'Villa',
    'commercial': 'Commercial',
    'land': 'Land',
    'other': 'Other',
}

year_built_choices = {
    '2020': '2020+',
    '2010': '2010+',
    '2000': '2000+',
    '1990': '1990+',
    '1980': '1980+',
    '1970': '1970+',
    '1960': '1960+',
    '1950': '1950+',
    '1940': '1940+',
    '1930': 'Before 1930',
}

# Common amenities that can be used to populate the Amenity model
common_amenities = [
    {'name': 'Swimming Pool', 'icon': 'fas fa-swimming-pool'},
    {'name': 'Gym/Fitness Center', 'icon': 'fas fa-dumbbell'},
    {'name': 'Parking Garage', 'icon': 'fas fa-car'},
    {'name': 'Garden/Yard', 'icon': 'fas fa-tree'},
    {'name': 'Balcony', 'icon': 'fas fa-building'},
    {'name': 'Terrace', 'icon': 'fas fa-home'},
    {'name': 'Fireplace', 'icon': 'fas fa-fire'},
    {'name': 'Air Conditioning', 'icon': 'fas fa-snowflake'},
    {'name': 'Central Heating', 'icon': 'fas fa-thermometer-half'},
    {'name': 'Dishwasher', 'icon': 'fas fa-utensils'},
    {'name': 'Washing Machine', 'icon': 'fas fa-tshirt'},
    {'name': 'Dryer', 'icon': 'fas fa-wind'},
    {'name': 'Microwave', 'icon': 'fas fa-microwave'},
    {'name': 'Refrigerator', 'icon': 'fas fa-refrigerator'},
    {'name': 'Oven', 'icon': 'fas fa-burn'},
    {'name': 'Security System', 'icon': 'fas fa-shield-alt'},
    {'name': 'Elevator', 'icon': 'fas fa-elevator'},
    {'name': 'Hardwood Floors', 'icon': 'fas fa-tree'},
    {'name': 'Tile Floors', 'icon': 'fas fa-th-large'},
    {'name': 'Carpet', 'icon': 'fas fa-rug'},
    {'name': 'Walk-in Closet', 'icon': 'fas fa-door-open'},
    {'name': 'Storage Room', 'icon': 'fas fa-boxes'},
    {'name': 'Laundry Room', 'icon': 'fas fa-soap'},
    {'name': 'Home Office', 'icon': 'fas fa-laptop-house'},
    {'name': 'Basement', 'icon': 'fas fa-arrow-down'},
    {'name': 'Attic', 'icon': 'fas fa-arrow-up'},
    {'name': 'Patio', 'icon': 'fas fa-chair'},
    {'name': 'Deck', 'icon': 'fas fa-home'},
    {'name': 'Fenced Yard', 'icon': 'fas fa-fence'},
    {'name': 'Sprinkler System', 'icon': 'fas fa-shower'},
    {'name': 'Solar Panels', 'icon': 'fas fa-solar-panel'},
    {'name': 'Smart Home', 'icon': 'fas fa-wifi'},
    {'name': 'Internet Ready', 'icon': 'fas fa-ethernet'},
    {'name': 'Cable Ready', 'icon': 'fas fa-tv'},
    {'name': 'Pet Friendly', 'icon': 'fas fa-paw'},
    {'name': 'Wheelchair Accessible', 'icon': 'fas fa-wheelchair'},
    {'name': 'Furnished', 'icon': 'fas fa-couch'},
    {'name': 'Utilities Included', 'icon': 'fas fa-lightbulb'},
    {'name': 'Gated Community', 'icon': 'fas fa-gate'},
    {'name': 'Concierge', 'icon': 'fas fa-concierge-bell'},
]

state_choices = {
    'AK': 'Alaska',
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'AS': 'American Samoa',
    'AZ': 'Arizona',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DC': 'District of Columbia',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'GU': 'Guam',
    'HI': 'Hawaii',
    'IA': 'Iowa',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'ME': 'Maine',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MO': 'Missouri',
    'MP': 'Northern Mariana Islands',
    'MS': 'Mississippi',
    'MT': 'Montana',
    'NA': 'National',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NE': 'Nebraska',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NV': 'Nevada',
    'NY': 'New York',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'PR': 'Puerto Rico',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VA': 'Virginia',
    'VI': 'Virgin Islands',
    'VT': 'Vermont',
    'WA': 'Washington',
    'WI': 'Wisconsin',
    'WV': 'West Virginia',
    'WY': 'Wyoming'
}
